version: '3.9'


services:

  db:
    image: postgres:14.3-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: sqlmodel_db